### ISSUE TITLE
Failed to activate the rst-preview package

### ISSUE THREAD

**Issue by bnmnetp** [lsegal/atom-rst-preview#22]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.4
**Thrown From**: [rst-preview](https://github.com/lsegal/atom-rst-preview) package, v1.1.0

### Stack Trace

Failed to activate the rst-preview package

```
At Module version mismatch. Expected 43, got 17.

Error: Module version mismatch. Expected 43, got 17.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/bmiller/.atom/packages/rst-preview/node_modules/pathwatcher/lib/main.js:6:13)
  at Object.<anonymous> (/Users/bmiller/.atom/packages/rst-preview/node_modules/pathwatcher/lib/main.js:207:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/bmiller/.atom/packages/rst-preview/lib/rst-preview-view.coffee:4:10)
  at Object.<anonymous> (/Users/bmiller/.atom/packages/rst-preview/lib/rst-preview-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/bmiller/.atom/packages/rst-preview/lib/rst-preview.coffee:4:18)
  at Object.<anonymous> (/Users/bmiller/.atom/packages/rst-preview/lib/rst-preview.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:691:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:239:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:754:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:00.8.0 rst-preview:show (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "rst-preview": {
    "grammars": [
      "text.restructuredtext"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
command-logger, v0.23.0
htmlhint, v1.1.2
language-latex, v0.6.1
language-restructuredtext, v0.5.0
latex, v0.23.0
linter, v0.12.1
rst-preview, v1.1.0
script, v2.21.0
seti-syntax, v0.4.0
seti-ui, v0.7.1
web-view, v0.3.0

# Dev
No dev packages
```

**Comment by lsegal** [comment]
Closing. Open a pull request to fix this, thanks!

**Comment by bnmnetp** [comment]
OK,  I don't have a fix.  I opened the PR from Atom because I was hoping someone with more expertise would have the time and inclination to fix the bug.  Oh well.
