### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Xanarkan** [lsegal/atom-rst-preview#46]
Hello, 

I can't install the plugin.

Microsoft Windows 10
Atom 1.15.0 x64
pandoc 1.19.2.1
language-restructuredtext 1.0.2

First I tried to install it with the built-in package installer and then with "apm".
Here is the log from Windows PowerShell:

```
PS C:\Users\Xanarkan\AppData\Local\atom\bin> apm install rst-preview
Installing rst-preview to C:\Users\Xanarkan\.atom\packages failed

> oniguruma@6.1.1 install C:\Users\Xanarkan\AppData\Local\Temp\apm-install-dir-11736-10868-1durza8\node_modules\rst-preview\node_modules\oniguruma
> node-gyp rebuild


C:\Users\Xanarkan\AppData\Local\Temp\apm-install-dir-11736-10868-1durza8\node_modules\rst-preview\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\nod
e_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
C:\Users\Xanarkan\AppData\Local\Temp\apm-install-dir-11736-10868-1durza8
`-- (empty)


npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\request\request.js:837:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\request\request.js:837:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\request\request.js:837:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\request\request.js:837:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\request\request.js:837:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\request\request.js:837:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\request\request.js:837:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\request\request.js:837:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\request\request.js:837:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\Xanarkan\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\Xanarkan\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Xanarkan\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Xanarkan\AppData\Local\Temp\apm-install-dir-11736-10868-1durza8\node_modules\rst-preview\node_modules\oniguruma
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Xanarkan\AppData\Local\Temp\apm-install-dir-11736-10868-1durza8\package.json'
npm WARN apm-install-dir-11736-10868-1durza8 No description
npm WARN apm-install-dir-11736-10868-1durza8 No repository field.
npm WARN apm-install-dir-11736-10868-1durza8 No README data
npm WARN apm-install-dir-11736-10868-1durza8 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Xanarkan\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Xanarkan\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Xanarkan\\.atom\\.apm\\.ap
mrc" "--userconfig" "C:\\Users\\Xanarkan\\.atom\\.apmrc" "install" "C:\\Users\\Xanarkan\\AppData\\Local\\Temp\\d-11736-10868-1wo44yc\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Xanarkan\AppData\Local\Temp\apm-install-dir-11736-10868-1durza8\npm-debug.log
npm ERR! code 1

PS C:\Users\Xanarkan\AppData\Local\atom\bin>
```

**Comment by Fenrihr** [comment]
I was having a similar problem: _rst-preview require **python2**_. I workaround installing Python 2.7 and adding the *.exe to my PATH. Changing the filename of `c:\Python27\python.exe` to `c:\Python27\python2.exe`. 

But this obly change the error to:
```
Installing rst-preview to C:\Users\Francisco\.atom\packages failed

> oniguruma@6.2.1 install C:\Users\FRANCI~1\AppData\Local\Temp\apm-install-dir-11931-7840-vdrrxq.bb7f8\node_modules\rst-preview\node_modules\oniguruma
> node-gyp rebuild

C:\Users\FRANCI~1\AppData\Local\Temp\apm-install-dir-11931-7840-vdrrxq.bb7f8\node_modules\rst-preview\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\Francisco\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Francisco\AppData\Local\atom\app-1.35.1\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
MSBUILD : error MSB3428: No se pudo cargar el componente "VCBuild.exe" de Visual C++. Para corregir este problema, 1) instale .NET Framework 2.0 SDK, 2) instale Microsoft Visual Studio 2005 o 3) agregue la ubicación del componente a la ruta de acceso del sistema si está instalado en otro lugar.  [C:\Users\FRANCI~1\AppData\Local\Temp\apm-install-dir-11931-7840-vdrrxq.bb7f8\node_modules\rst-preview\node_modules\oniguruma\build\binding.sln]

npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated coffee-script@1.9.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\Francisco\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'C:\\Users\\Francisco\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 C:\Python27\python2.EXE
gyp verb check python version `C:\Python27\python2.EXE -c "import platform; print(platform.python_version());"` returned: "2.7.16\r\n"
gyp verb get node dir compiling against --target node version: 2.0.18
gyp verb command install [ '2.0.18' ]
gyp verb install input version string "2.0.18"
gyp verb install installing version: iojs-2.0.18
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: iojs-2.0.18
gyp verb build dir attempting to create "build" dir: C:\Users\FRANCI~1\AppData\Local\Temp\apm-install-dir-11931-7840-vdrrxq.bb7f8\node_modules\rst-preview\node_modules\oniguruma\build
gyp verb build dir "build" dir needed to be created? C:\Users\FRANCI~1\AppData\Local\Temp\apm-install-dir-11931-7840-vdrrxq.bb7f8\node_modules\rst-preview\node_modules\oniguruma\build
gyp verb build/config.gypi creating config file
gyp sill build/config.gypi { target_defaults:
gyp sill build/config.gypi    { cflags: [],
gyp sill build/config.gypi      default_configuration: 'Release',
gyp sill build/config.gypi      defines: [],
gyp sill build/config.gypi      include_dirs: [],
gyp sill build/config.gypi      libraries: [] },
gyp sill build/config.gypi   variables:
gyp sill build/config.gypi    { asan: 0,
gyp sill build/config.gypi      coverage: false,
gyp sill build/config.gypi      debug_devtools: 'node',
gyp sill build/config.gypi      debug_http2: false,
gyp sill build/config.gypi      debug_nghttp2: false,
gyp sill build/config.gypi      force_dynamic_crt: 0,
gyp sill build/config.gypi      host_arch: 'x64',
gyp sill build/config.gypi      icu_data_file: 'icudt59l.dat',
gyp sill build/config.gypi      icu_data_in: '..\\..\\deps/icu-small\\source/data/in\\icudt59l.dat',
gyp sill build/config.gypi      icu_endianness: 'l',
gyp sill build/config.gypi      icu_gyp_path: 'tools/icu/icu-generic.gyp',
gyp sill build/config.gypi      icu_locales: 'en,root',
gyp sill build/config.gypi      icu_path: 'deps/icu-small',
gyp sill build/config.gypi      icu_small: true,
gyp sill build/config.gypi      icu_ver_major: '59',
gyp sill build/config.gypi      node_byteorder: 'little',
gyp sill build/config.gypi      node_enable_d8: false,
gyp sill build/config.gypi      node_enable_v8_vtunejit: false,
gyp sill build/config.gypi      node_install_npm: true,
gyp sill build/config.gypi      node_module_version: 57,
gyp sill build/config.gypi      node_no_browser_globals: false,
gyp sill build/config.gypi      node_prefix: '/usr/local',
gyp sill build/config.gypi      node_release_urlbase: 'https://nodejs.org/download/release/',
gyp sill build/config.gypi      node_shared: false,
gyp sill build/config.gypi      node_shared_cares: false,
gyp sill build/config.gypi      node_shared_http_parser: false,
gyp sill build/config.gypi      node_shared_libuv: false,
gyp sill build/config.gypi      node_shared_openssl: false,
gyp sill build/config.gypi      node_shared_zlib: false,
gyp sill build/config.gypi      node_tag: '',
gyp sill build/config.gypi      node_use_bundled_v8: true,
gyp sill build/config.gypi      node_use_dtrace: false,
gyp sill build/config.gypi      node_use_etw: true,
gyp sill build/config.gypi      node_use_lttng: false,
gyp sill build/config.gypi      node_use_openssl: true,
gyp sill build/config.gypi      node_use_perfctr: true,
gyp sill build/config.gypi      node_use_v8_platform: true,
gyp sill build/config.gypi      node_without_node_options: false,
gyp sill build/config.gypi      openssl_fips: '',
gyp sill build/config.gypi      openssl_no_asm: 0,
gyp sill build/config.gypi      shlib_suffix: 'so.57',
gyp sill build/config.gypi      target_arch: 'x64',
gyp sill build/config.gypi      v8_enable_gdbjit: 0,
gyp sill build/config.gypi      v8_enable_i18n_support: 1,
gyp sill build/config.gypi      v8_enable_inspector: 1,
gyp sill build/config.gypi      v8_no_strict_aliasing: 1,
gyp sill build/config.gypi      v8_optimized_debug: 0,
gyp sill build/config.gypi      v8_promise_internal_field_count: 1,
gyp sill build/config.gypi      v8_random_seed: 0,
gyp sill build/config.gypi      v8_trace_maps: 0,
gyp sill build/config.gypi      v8_use_snapshot: true,
gyp sill build/config.gypi      want_separate_host_toolset: 0,
gyp sill build/config.gypi      nodedir: 'C:\\Users\\Francisco\\.atom\\.node-gyp\\.node-gyp\\iojs-2.0.18',
gyp sill build/config.gypi      copy_dev_lib: true,
gyp sill build/config.gypi      standalone_static_library: 1,
gyp sill build/config.gypi      access: '',
gyp sill build/config.gypi      allow_same_version: '',
gyp sill build/config.gypi      also: '',
gyp sill build/config.gypi      always_auth: '',
gyp sill build/config.gypi      audit: 'true',
gyp sill build/config.gypi      auth_type: 'legacy',
gyp sill build/config.gypi      bin_links: 'true',
gyp sill build/config.gypi      browser: '',
gyp sill build/config.gypi      ca: '',
gyp sill build/config.gypi      cache: 'C:\\Users\\Francisco\\.atom\\.apm',
gyp sill build/config.gypi      cache_lock_retries: '10',
gyp sill build/config.gypi      cache_lock_stale: '60000',
gyp sill build/config.gypi      cache_lock_wait: '10000',
gyp sill build/config.gypi      cache_max: 'Infinity',
gyp sill build/config.gypi      cache_min: '10',
gyp sill build/config.gypi      cert: '',
gyp sill build/config.gypi      cidr: '',
gyp sill build/config.gypi      color: 'true',
gyp sill build/config.gypi      commit_hooks: 'true',
gyp sill build/config.gypi      depth: 'Infinity',
gyp sill build/config.gypi      description: 'true',
gyp sill build/config.gypi      dev: '',
gyp sill build/config.gypi      dist_url: 'https://atom.io/download/electron',
gyp sill build/config.gypi      dry_run: '',
gyp sill build/config.gypi      editor: 'notepad.exe',
gyp sill build/config.gypi      engine_strict: '',
gyp sill build/config.gypi      fetch_retries: '2',
gyp sill build/config.gypi      fetch_retry_factor: '10',
gyp sill build/config.gypi      fetch_retry_maxtimeout: '60000',
gyp sill build/config.gypi      fetch_retry_mintimeout: '10000',
gyp sill build/config.gypi      force: '',
gyp sill build/config.gypi      git: 'git',
gyp sill build/config.gypi      git_tag_version: 'true',
gyp sill build/config.gypi      global: '',
gyp sill build/config.gypi      globalconfig: 'C:\\Users\\Francisco\\.atom\\.apm\\.apmrc',
gyp sill build/config.gypi      globalignorefile: 'C:\\Users\\Francisco\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\bin\\etc\\npmignore',
gyp sill build/config.gypi      global_style: 'true',
gyp sill build/config.gypi      group: '',
gyp sill build/config.gypi      ham_it_up: '',
gyp sill build/config.gypi      heading: 'npm',
gyp sill build/config.gypi      https_proxy: '',
gyp sill build/config.gypi      if_present: '',
gyp sill build/config.gypi      ignore_prepublish: '',
gyp sill build/config.gypi      ignore_scripts: '',
gyp sill build/config.gypi      init_author_email: '',
gyp sill build/config.gypi      init_author_name: '',
gyp sill build/config.gypi      init_author_url: '',
gyp sill build/config.gypi      init_license: 'ISC',
gyp sill build/config.gypi      init_module: 'C:\\Users\\Francisco\\.atom\\.node-gyp\\.npm-init.js',
gyp sill build/config.gypi      init_version: '1.0.0',
gyp sill build/config.gypi      json: '',
gyp sill build/config.gypi      key: '',
gyp sill build/config.gypi      legacy_bundling: '',
gyp sill build/config.gypi      link: '',
gyp sill build/config.gypi      local_address: '',
gyp sill build/config.gypi      logs_max: '10',
gyp sill build/config.gypi      long: '',
gyp sill build/config.gypi      maxsockets: '50',
gyp sill build/config.gypi      message: '%s',
gyp sill build/config.gypi      metrics_registry: 'https://registry.npmjs.org/',
gyp sill build/config.gypi      node_gyp: 'C:\\Users\\Francisco\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\bin\\\\..\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp sill build/config.gypi      node_options: '',
gyp sill build/config.gypi      node_version: '8.9.3',
gyp sill build/config.gypi      no_proxy: '',
gyp sill build/config.gypi      offline: '',
gyp sill build/config.gypi      onload_script: '',
gyp sill build/config.gypi      only: '',
gyp sill build/config.gypi      optional: 'true',
gyp sill build/config.gypi      otp: '',
gyp sill build/config.gypi      package_lock: 'true',
gyp sill build/config.gypi      package_lock_only: '',
gyp sill build/config.gypi      parseable: '',
gyp sill build/config.gypi      prefer_offline: '',
gyp sill build/config.gypi      prefer_online: '',
gyp sill build/config.gypi      prefix: 'C:\\Users\\Francisco\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\bin',
gyp sill build/config.gypi      production: '',
gyp sill build/config.gypi      progress: '',
gyp sill build/config.gypi      read_only: '',
gyp sill build/config.gypi      rebuild_bundle: 'true',
gyp sill build/config.gypi      registry: 'https://registry.npmjs.org/',
gyp sill build/config.gypi      rollback: 'true',
gyp sill build/config.gypi      runtime: 'electron',
gyp sill build/config.gypi      save: 'true',
gyp sill build/config.gypi      save_bundle: '',
gyp sill build/config.gypi      save_dev: '',
gyp sill build/config.gypi      save_exact: '',
gyp sill build/config.gypi      save_optional: '',
gyp sill build/config.gypi      save_prefix: '^',
gyp sill build/config.gypi      save_prod: '',
gyp sill build/config.gypi      scope: '',
gyp sill build/config.gypi      scripts_prepend_node_path: 'warn-only',
gyp sill build/config.gypi      script_shell: '',
gyp sill build/config.gypi      searchexclude: '',
gyp sill build/config.gypi      searchlimit: '20',
gyp sill build/config.gypi      searchopts: '',
gyp sill build/config.gypi      searchstaleness: '900',
gyp sill build/config.gypi      send_metrics: '',
gyp sill build/config.gypi      shell: 'C:\\WINDOWS\\system32\\cmd.exe',
gyp sill build/config.gypi      shrinkwrap: 'true',
gyp sill build/config.gypi      sign_git_commit: '',
gyp sill build/config.gypi      sign_git_tag: '',
gyp sill build/config.gypi      sso_poll_frequency: '500',
gyp sill build/config.gypi      sso_type: 'oauth',
gyp sill build/config.gypi      strict_ssl: 'true',
gyp sill build/config.gypi      tag: 'latest',
gyp sill build/config.gypi      tag_version_prefix: 'v',
gyp sill build/config.gypi      target: '2.0.18',
gyp sill build/config.gypi      timing: '',
gyp sill build/config.gypi      tmp: 'C:\\Users\\FRANCI~1\\AppData\\Local\\Temp',
gyp sill build/config.gypi      umask: '0000',
gyp sill build/config.gypi      unicode: '',
gyp sill build/config.gypi      unsafe_perm: 'true',
gyp sill build/config.gypi      update_notifier: 'true',
gyp sill build/config.gypi      usage: '',
gyp sill build/config.gypi      user: '',
gyp sill build/config.gypi      userconfig: 'C:\\Users\\Francisco\\.atom\\.apmrc',
gyp sill build/config.gypi      user_agent: 'npm/6.2.0 node/v8.9.3 win32 x64',
gyp sill build/config.gypi      version: '',
gyp sill build/config.gypi      versions: '',
gyp sill build/config.gypi      viewer: 'browser' } }
gyp verb build/config.gypi writing out config file: C:\Users\FRANCI~1\AppData\Local\Temp\apm-install-dir-11931-7840-vdrrxq.bb7f8\node_modules\rst-preview\node_modules\oniguruma\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\FRANCI~1\AppData\Local\Temp\apm-install-dir-11931-7840-vdrrxq.bb7f8\node_modules\rst-preview\node_modules\oniguruma\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\FRANCI~1\AppData\Local\Temp\apm-install-dir-11931-7840-vdrrxq.bb7f8\node_modules\rst-preview\node_modules\oniguruma\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python2.EXE
gyp info spawn args [ 'C:\\Users\\Francisco\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\FRANCI~1\\AppData\\Local\\Temp\\apm-install-dir-11931-7840-vdrrxq.bb7f8\\node_modules\\rst-preview\\node_modules\\oniguruma\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Francisco\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Francisco\\.atom\\.node-gyp\\.node-gyp\\iojs-2.0.18\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Francisco\\.atom\\.node-gyp\\.node-gyp\\iojs-2.0.18',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Francisco\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\FRANCI~1\\AppData\\Local\\Temp\\apm-install-dir-11931-7840-vdrrxq.bb7f8\\node_modules\\rst-preview\\node_modules\\oniguruma',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\FRANCI~1\\AppData\\Local\\Temp\\apm-install-dir-11931-7840-vdrrxq.bb7f8\\node_modules\\rst-preview\\node_modules\\oniguruma\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\Francisco\.atom\.node-gyp\.node-gyp\iojs-2.0.18
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp verb "Release" dir needed to be created? C:\Users\Francisco\.atom\.node-gyp\.node-gyp\iojs-2.0.18\Release
gyp verb copying "iojs.lib" for x64 C:\Users\Francisco\.atom\.node-gyp\.node-gyp\iojs-2.0.18\Release\iojs.lib
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Francisco\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Users\\Francisco\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Francisco\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\FRANCI~1\AppData\Local\Temp\apm-install-dir-11931-7840-vdrrxq.bb7f8\node_modules\rst-preview\node_modules\oniguruma
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\FRANCI~1\AppData\Local\Temp\apm-install-dir-11931-7840-vdrrxq.bb7f8\package.json'
npm WARN apm-install-dir-11931-7840-vdrrxq.bb7f8 No description
npm WARN apm-install-dir-11931-7840-vdrrxq.bb7f8 No repository field.
npm WARN apm-install-dir-11931-7840-vdrrxq.bb7f8 No README data
npm WARN apm-install-dir-11931-7840-vdrrxq.bb7f8 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oniguruma@6.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@6.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Francisco\.atom\.apm\_logs\2019-04-01T20_44_08_305Z-debug.log
```
