### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by sfggeogis** [lsegal/atom-rst-preview#53]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [rst-preview](https://github.com/lsegal/atom-rst-preview) package 1.3.1

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:160

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:715:26)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Socket.Writable.write (_stream_writable.js:245:11)
    at Socket.write (net.js:661:40)
    at RstPreviewView.module.exports.RstPreviewView.renderRstText (/packages/rst-preview/lib/rst-preview-view.coffee:137:17)
    at RstPreviewView.module.exports.RstPreviewView.renderRst (/packages/rst-preview/lib/rst-preview-view.coffee:128:8)
    at /packages/rst-preview/lib/rst-preview-view.coffee:64:10
    at RstPreviewView.module.exports.RstPreviewView.resolveEditor (/packages/rst-preview/lib/rst-preview-view.coffee:71:7)
    at RstPreviewView.module.exports.RstPreviewView.attached (/packages/rst-preview/lib/rst-preview-view.coffee:25:8)
    at HTMLDivElement.View.element.attached (/packages/rst-preview/node_modules/space-pen/lib/space-pen.js:164:63)
    at HTMLDivElement.CustomElementPrototype.attachedCallback (/packages/rst-preview/node_modules/space-pen/lib/space-pen.js:51:55)
    at HTMLElement.PaneElement.activeItemChanged (/app.asar/src/pane-element.js:156:24)
    at Function.module.exports.Emitter.simpleDispatch (C:/ProgramData/v.pascual/atom/app-1.22.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:/ProgramData/v.pascual/atom/app-1.22.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.setActiveItem (C:/ProgramData/v.pascual/atom/app-1.22.0/resources/app/src/pane.js:435:26)
    at Pane.addItem (C:/ProgramData/v.pascual/atom/app-1.22.0/resources/app/src/pane.js:636:43)
    at Pane.activateItem (C:/ProgramData/v.pascual/atom/app-1.22.0/resources/app/src/pane.js:574:18)
    at Workspace.<anonymous> (C:/ProgramData/v.pascual/atom/app-1.22.0/resources/app/src/workspace.js:1175:20)
    at Generator.next (<anonymous>)
    at step (C:/ProgramData/v.pascual/atom/app-1.22.0/resources/app/src/workspace.js:11:279)
```

### Commands

```
  4x -2:56.2.0 core:move-left (input.hidden-input)
     -2:55.3.0 core:move-right (input.hidden-input)
  8x -2:55 core:backspace (input.hidden-input)
  3x -2:49.2.0 core:move-right (input.hidden-input)
 22x -2:48.5.0 core:select-left (input.hidden-input)
     -2:46.1.0 core:copy (input.hidden-input)
     -2:45.9.0 core:move-down (input.hidden-input)
     -2:45.3.0 core:paste (input.hidden-input)
     -2:45 core:move-down (input.hidden-input)
     -2:44.5.0 core:paste (input.hidden-input)
     -2:44.2.0 core:move-down (input.hidden-input)
     -2:43.7.0 core:paste (input.hidden-input)
     -2:40.3.0 core:save (input.hidden-input)
     -2:08.6.0 github:toggle-git-tab (input.hidden-input)
     -1:47.2.0 editor:newline (input.hidden-input)
  2x -0:34.9.0 rst-preview:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-minify 0.8.0 
atom-monokai 0.10.9 
atom-ternjs 0.18.3 
file-icons 2.1.13 
language-restructuredtext 1.1.0 
pandoc 0.2.2 
pandoc-convert 1.1.1 
pretty-json 1.6.4 
rst-preview 1.3.1 
rst-preview-pandoc 0.1.12 
```

**Comment by paucoma** [comment]
Got the same error, in my case, I did not have pandoc in the PATH, I had installed the portable version of pandoc.

**Added Pandoc to the path**, Restarted Atom, All ok
